CREATE TABLE [dbo].[DimCustomer] (
    [CustomerKey]         INT          IDENTITY (1, 1) NOT NULL,
    [CustomerNumber]      VARCHAR (30) NOT NULL,
    [CustomerSequence]    VARCHAR (10) NOT NULL,
    [CustomerName]        VARCHAR (80) NOT NULL,
    [Address1]            VARCHAR (50) NULL,
    [Address2]            VARCHAR (50) NULL,
    [Address3]            VARCHAR (50) NULL,
    [Address4]            VARCHAR (50) NULL,
    [City]                VARCHAR (30) NULL,
    [State]               VARCHAR (30) NULL,
    [Zip]                 VARCHAR (30) NULL,
    [Country]             VARCHAR (30) NULL,
    [Contact1]            VARCHAR (30) NULL,
    [Contact2]            VARCHAR (30) NULL,
    [Contact3]            VARCHAR (30) NULL,
    [Phone1]              VARCHAR (25) NULL,
    [Phone2]              VARCHAR (25) NULL,
    [Phone3]              VARCHAR (25) NULL,
    [Fax]                 VARCHAR (25) NULL,
    [InternalEmail]       VARCHAR (30) NULL,
    [ExternalEmail]       VARCHAR (30) NULL,
    [Carrier]             VARCHAR (30) NULL,
    [CarrierAccount]      VARCHAR (30) NULL,
    [FacilityID]          VARCHAR (30) NULL,
    [CustomerTypeCode]    VARCHAR (25) NULL,
    [CustomerType]        VARCHAR (50) NULL,
    [TaxCode]             VARCHAR (6)  NULL,
    [EndUserTypeCode]     VARCHAR (6)  NULL,
    [EndUserType]         VARCHAR (50) NULL,
    [CustomerCreatedDate] DATETIME     NULL,
    CONSTRAINT [PK_DimCustomer_CustomerKey] PRIMARY KEY CLUSTERED ([CustomerKey] ASC)
);

