CREATE TABLE [dbo].[IHD] (
    [Invoice_No]      NVARCHAR (6)   NOT NULL,
    [Customer_No]     NVARCHAR (5)   NOT NULL,
    [Shipto_No]       NVARCHAR (6)   NULL,
    [Shipto_Name]     NVARCHAR (30)  NULL,
    [Shipto_Add1]     NVARCHAR (30)  NULL,
    [Shipto_Add2]     NVARCHAR (30)  NULL,
    [Shipto_Add3]     NVARCHAR (30)  NULL,
    [Shipto_Add4]     NVARCHAR (30)  NULL,
    [Order_No]        NVARCHAR (7)   NULL,
    [Date_Wanted]     NVARCHAR (10)  NULL,
    [Invoice_Date]    DATETIME       NULL,
    [Inv_Mon]         NVARCHAR (7)   NULL,
    [PO_No]           NVARCHAR (12)  NULL,
    [Salesman_No]     NVARCHAR (3)   NULL,
    [Item_Total]      FLOAT (53)     NULL,
    [Discount]        FLOAT (53)     NULL,
    [Tax]             FLOAT (53)     NULL,
    [Freight]         FLOAT (53)     NULL,
    [Other_Charges]   FLOAT (53)     NULL,
    [Shipto_Zip]      NVARCHAR (5)   NULL,
    [Order_Date]      DATETIME       NULL,
    [Sales_Tax_State] NVARCHAR (2)   NULL,
    [Sales_Tax_Code]  NVARCHAR (4)   NULL,
    [Group]           NVARCHAR (3)   NULL,
    [Sale_Region]     NVARCHAR (3)   NULL,
    [Euro_Adj]        FLOAT (53)     NULL,
    [Cost]            FLOAT (53)     NULL,
    [IHD_Add1]        NVARCHAR (50)  NULL,
    [IHD_Add2]        NVARCHAR (50)  NULL,
    [IHD_Add3]        NVARCHAR (50)  NULL,
    [IHD_Add4]        NVARCHAR (50)  NULL,
    [City]            NVARCHAR (50)  NULL,
    [State]           NVARCHAR (50)  NULL,
    [Zip]             NVARCHAR (50)  NULL,
    [Inv_ContractNo]  NVARCHAR (5)   NULL,
    [CustType]        NVARCHAR (255) NULL
);

