CREATE TABLE [dbo].[INVENT] (
    [Item_no]       NVARCHAR (10) NOT NULL,
    [Description]   NVARCHAR (28) NULL,
    [QOH]           INT           NULL,
    [QOO]           INT           NULL,
    [QC]            INT           NULL,
    [UM]            NVARCHAR (2)  NULL,
    [DateEntered]   DATETIME      NULL,
    [Supplier]      NVARCHAR (6)  NULL,
    [Supplier2]     NVARCHAR (6)  NULL,
    [EstDelDate]    NVARCHAR (10) NULL,
    [Price]         INT           NULL,
    [Tax]           NVARCHAR (1)  NULL,
    [Cost_current]  FLOAT (53)    NULL,
    [Cost_previous] FLOAT (53)    NULL,
    [QOH_current]   INT           NULL,
    [QOH_previous]  INT           NULL,
    [Group]         NVARCHAR (2)  NULL,
    [Lot]           NVARCHAR (1)  NULL,
    [YTD_use]       INT           NULL,
    [PrYr_use]      INT           NULL,
    [Date_last_inv] DATETIME      NULL,
    [CEflag]        NVARCHAR (1)  NULL,
    [Comm]          FLOAT (53)    NULL,
    [TravelerCd]    NVARCHAR (2)  NULL,
    [CommType]      NVARCHAR (1)  NULL,
    [YTD_Ext]       FLOAT (53)    NULL,
    [PrYr_Ext]      FLOAT (53)    NULL
);

