CREATE LOGIN [DWUser]
    WITH PASSWORD = N'vm<jibhFreyrig{.vmzoujtomsFT7_&#$!~<6 Se{pwe;v|g', SID = 0x4BD4E4932BDB484BBC2E3E8D9187BEE0, DEFAULT_DATABASE = [KPIDW], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

